num=int(input("Digite um número de três dígitos: "))
centena=int(num%10)
dezena=int((num%100)/10)
unidade=int(num/100)
print("Número lido:", num)
print("Número Gerado:", centena*100+dezena*10+unidade)